// Code generated from Fuzzball 7 include/tunelist.h. DO NOT EDIT.
// Regenerate with: go generate ./internal/tune

package tune

import (
	"time"

	"github.com/FatmanUK/fuzzball_emerald/internal/ref"
)

// params is the full parameter table, ordered by name.
var params = []Param{
	{
		Name:      "7bit_other_names",
		Label:     "Limit exit/room/muf names to 7-bit characters",
		Group:     "Charset",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "7bit_thing_names",
		Label:     "Limit thing names to 7-bit characters",
		Group:     "Charset",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "addpennies_muf_mlev",
		Label:     "Mucker Level required to create/destroy pennies",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 2},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "aging_time",
		Label:     "When to considered an object old and unused",
		Group:     "Database",
		Type:      TypeTimespan,
		Default:   Value{Span: 7776000 * time.Second},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "allow_listeners",
		Label:     "Allow programs to listen to player output",
		Group:     "Listeners",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "allow_listeners_env",
		Label:     "Allow listeners down environment",
		Group:     "Listeners",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "allow_listeners_obj",
		Label:     "Allow objects to be listeners",
		Group:     "Listeners",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "allow_zombies",
		Label:     "Enable Zombie things to relay what they hear",
		Group:     "Misc",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "autolink_actions",
		Label:     "Automatically link @actions to NIL",
		Group:     "Misc",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "autolook_cmd",
		Label:     "Room entry look command",
		Group:     "Commands",
		Type:      TypeString,
		Default:   Value{Str: "look"},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "clean_interval",
		Label:     "Interval between memory/object cleanups",
		Group:     "Tuning",
		Type:      TypeTimespan,
		Default:   Value{Span: 900 * time.Second},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "cmd_log_threshold_msec",
		Label:     "Log commands that take longer than X millisecs",
		Group:     "Logging",
		Type:      TypeInteger,
		Default:   Value{Num: 1000},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "cmd_only_overrides",
		Label:     "Disable all built-in commands except wizard !overrides",
		Group:     "Commands",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "command_burst_size",
		Label:     "Max. commands per burst before limiter engages",
		Group:     "Spam Limits",
		Type:      TypeInteger,
		Default:   Value{Num: 500},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "command_time_msec",
		Label:     "Millisecs per spam limiter time period",
		Group:     "Spam Limits",
		Type:      TypeInteger,
		Default:   Value{Num: 1000},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "commands_per_time",
		Label:     "Commands allowed per time period during limit",
		Group:     "Spam Limits",
		Type:      TypeInteger,
		Default:   Value{Num: 2},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "compatible_priorities",
		Label:     "Use legacy exit priority levels on things",
		Group:     "Database",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "connect_fail_mesg",
		Label:     "Failed player connect message",
		Group:     "Connecting",
		Type:      TypeString,
		Default:   Value{Str: "Either that player does not exist, or has a different password."},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
	},
	{
		Name:      "consistent_lock_source",
		Label:     "Maintain trigger as lock source in TESTLOCK",
		Group:     "MUF",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "cpennies",
		Label:     "Currency name, capitalized, plural",
		Group:     "Currency",
		Type:      TypeString,
		Default:   Value{Str: "Pennies"},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "cpenny",
		Label:     "Currency name, capitalized",
		Group:     "Currency",
		Type:      TypeString,
		Default:   Value{Str: "Penny"},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "dark_sleepers",
		Label:     "Make sleeping players dark",
		Group:     "Dark",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "dbdump_warning",
		Label:     "Enable warnings for upcoming database dumps",
		Group:     "DB Dumps",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
		Inert:     "saving never blocks the world",
	},
	{
		Name:       "default_room_parent",
		Label:      "Place to parent new rooms to",
		Group:      "Database",
		Type:       TypeDbref,
		Default:    Value{Ref: ref.GlobalEnvironment},
		ReadMLev:   0,
		WriteMLev:  4,
		ObjType:    ref.TypeRoom,
		HasObjType: true,
	},
	{
		Name:      "description_default",
		Label:     "Default description",
		Group:     "Misc",
		Type:      TypeString,
		Default:   Value{Str: "You see nothing special."},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "diskbase_propvals",
		Label:     "Enable property value diskbasing (req. restart)",
		Group:     "DB Dumps",
		Module:    "DISKBASE",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
		Inert:     "DISKBASE is gone; properties live in Postgres",
	},
	{
		Name:      "do_mpi_parsing",
		Label:     "Parse MPI strings in messages",
		Group:     "MPI",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "do_welcome_parsing",
		Label:     "Parse MPI in welcome file or proplist",
		Group:     "MPI",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "dump_interval",
		Label:     "Interval between dumps",
		Group:     "DB Dumps",
		Type:      TypeTimespan,
		Default:   Value{Span: 14400 * time.Second},
		ReadMLev:  0,
		WriteMLev: 4,
		Inert:     "superseded by continuous write-behind; see flush_interval",
	},
	{
		Name:      "dump_warntime",
		Label:     "Interval between warning and dump",
		Group:     "DB Dumps",
		Type:      TypeTimespan,
		Default:   Value{Span: 120 * time.Second},
		ReadMLev:  0,
		WriteMLev: 4,
		Inert:     "no dump pause to warn about",
	},
	{
		Name:      "dumpdone_mesg",
		Label:     "Database dump finished message",
		Group:     "DB Dumps",
		Type:      TypeString,
		Default:   Value{Str: "## Save complete. ##"},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
		Inert:     "saving never blocks the world",
	},
	{
		Name:      "dumpdone_warning",
		Label:     "Notify when database dump complete",
		Group:     "DB Dumps",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
		Inert:     "saving never blocks the world",
	},
	{
		Name:      "dumping_mesg",
		Label:     "Database dump started message",
		Group:     "DB Dumps",
		Type:      TypeString,
		Default:   Value{Str: "## Pausing to save database. This may take a while. ##"},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
		Inert:     "saving never blocks the world",
	},
	{
		Name:      "dumpwarn_mesg",
		Label:     "Database dump finished message",
		Group:     "DB Dumps",
		Type:      TypeString,
		Default:   Value{Str: "## Game will pause to save the database in a few minutes. ##"},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
		Inert:     "no dump pause to warn about",
	},
	{
		Name:      "enable_home",
		Label:     "Enable 'home' command",
		Group:     "Commands",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "enable_prefix",
		Label:     "Enable prefix actions",
		Group:     "Commands",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "exit_cost",
		Label:     "Cost to create an exit",
		Group:     "Costs",
		Type:      TypeInteger,
		Default:   Value{Num: 1},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "exit_darking",
		Label:     "Allow players to set exits dark",
		Group:     "Dark",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "expanded_debug_trace",
		Label:     "MUF debug trace shows array contents",
		Group:     "MUF",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "file_connection_help",
		Label:     "'help' before login",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/connect-help.txt"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_credits",
		Label:     "Acknowledgements",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/credits.txt"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_editor_help",
		Label:     "Editor help",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/edit-help.txt"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_help",
		Label:     "'help' main content",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/help.txt"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_help_dir",
		Label:     "'help' topic directory",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/help"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_info_dir",
		Label:     "'info' topic directory",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/info/"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_log_cmd_times",
		Label:     "Command times",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/cmd-times"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_commands",
		Label:     "Player commands",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/commands"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_gripes",
		Label:     "Player gripes",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/gripes"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_malloc",
		Label:     "Memory allocations",
		Group:     "Files",
		Module:    "MEMPROF",
		Type:      TypeString,
		Default:   Value{Str: "logs/malloc"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_muf_errors",
		Label:     "MUF compile errors and warnings",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/muf-errors"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_programs",
		Label:     "Text of changed programs",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/programs"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_sanfix",
		Label:     "Database fixes",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/sanfixed"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_sanity",
		Label:     "Database corruption and errors",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/sanity"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_status",
		Label:     "System errors and stats",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/status"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_stderr",
		Label:     "Server error redirect",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/fbmuck.err"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_stdout",
		Label:     "Server output redirect",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/fbmuck"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_log_user",
		Label:     "MUF-writable messages",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "logs/user"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "file_man",
		Label:     "'man' main content",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/man.txt"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_man_dir",
		Label:     "'man' topic directory",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/man"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_motd",
		Label:     "Message of the day",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/motd.txt"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_mpihelp",
		Label:     "'mpi' main content",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/mpihelp.txt"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_mpihelp_dir",
		Label:     "'mpi' topic directory",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/mpihelp"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_news",
		Label:     "'news' main content",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/news.txt"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_news_dir",
		Label:     "'news' topic directory",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/news"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "file_welcome_screen",
		Label:     "Opening screen",
		Group:     "Files",
		Type:      TypeString,
		Default:   Value{Str: "data/welcome.txt"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Inert:     "help texts live in Postgres, not files",
	},
	{
		Name:      "force_mlev1_name_notify",
		Label:     "MUF notify prepends username for ML1 programs",
		Group:     "MUF",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "free_frames_pool",
		Label:     "Size of allocated MUF process frame pool",
		Group:     "Tuning",
		Type:      TypeInteger,
		Default:   Value{Num: 8},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "gender_prop",
		Label:     "Property name used for pronoun substitutions",
		Group:     "Properties",
		Type:      TypeString,
		Default:   Value{Str: "sex"},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "huh_mesg",
		Label:     "Unrecognized command warning",
		Group:     "Misc",
		Type:      TypeString,
		Default:   Value{Str: "Huh?  (Type \"help\" for help.)"},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "idle_boot_mesg",
		Label:     "Boot message given to users idling out",
		Group:     "Idle Boot",
		Type:      TypeString,
		Default:   Value{Str: "Autodisconnecting for inactivity."},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "idle_ping_enable",
		Label:     "Enable server side keepalive pings",
		Group:     "Idle Boot",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "idle_ping_time",
		Label:     "Server side keepalive time in seconds",
		Group:     "Idle Boot",
		Type:      TypeTimespan,
		Default:   Value{Span: 55 * time.Second},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "idleboot",
		Label:     "Enable booting of idle players",
		Group:     "Idle Boot",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "ieee_bounds_handling",
		Label:     "Use IEEE standard for operations with INF and NAN",
		Group:     "MUF",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "ignore_bidirectional",
		Label:     "Enable bidirectional ignore",
		Group:     "Misc",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  3,
		WriteMLev: 4,
	},
	{
		Name:      "ignore_support",
		Label:     "Enable support for @ignoring players",
		Group:     "Misc",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  3,
		WriteMLev: 4,
	},
	{
		Name:      "instr_slice",
		Label:     "Max. uninterrupted instructions per timeslice",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 2000},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "leave_mesg",
		Label:     "Logoff message for QUIT",
		Group:     "Misc",
		Type:      TypeString,
		Default:   Value{Str: "Come back later!"},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "legacy_password_hash",
		Label:     "Use Legacy (insecure, compatible) Password Hash",
		Group:     "Misc",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "link_cost",
		Label:     "Cost to link an exit",
		Group:     "Costs",
		Type:      TypeInteger,
		Default:   Value{Num: 1},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "listen_mlev",
		Label:     "Mucker Level required for Listener programs",
		Group:     "Listeners",
		Type:      TypeInteger,
		Default:   Value{Num: 3},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "lock_envcheck",
		Label:     "Locks check environment for properties",
		Group:     "Properties",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "log_commands",
		Label:     "Log player commands",
		Group:     "Logging",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "log_failed_commands",
		Label:     "Log unrecognized commands",
		Group:     "Logging",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "log_interactive",
		Label:     "Log text sent to MUF",
		Group:     "Logging",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "log_programs",
		Label:     "Log programs every time they are saved",
		Group:     "Logging",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "lookup_cost",
		Label:     "Cost to lookup a player name",
		Group:     "Costs",
		Type:      TypeInteger,
		Default:   Value{Num: 0},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:       "lost_and_found",
		Label:      "Place for things without a home",
		Group:      "Database",
		Type:       TypeDbref,
		Default:    Value{Ref: ref.GlobalEnvironment},
		ReadMLev:   0,
		WriteMLev:  4,
		ObjType:    ref.TypeRoom,
		HasObjType: true,
	},
	{
		Name:      "m3_huh",
		Label:     "Enable huh? to call an exit named \"huh?\" and set M3, with full command string",
		Group:     "Misc",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  3,
		WriteMLev: 4,
	},
	{
		Name:      "max_force_level",
		Label:     "Max. number of forces processed within a command",
		Group:     "Misc",
		Type:      TypeInteger,
		Default:   Value{Num: 1},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "max_instr_count",
		Label:     "Max. MUF instruction run length for ML1",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 20000},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
	},
	{
		Name:      "max_interp_recursion",
		Label:     "Max. MUF interpreter recursion",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 8},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
	},
	{
		Name:      "max_loaded_objs",
		Label:     "Max. percent of proploaded database objects",
		Group:     "Tuning",
		Module:    "DISKBASE",
		Type:      TypeInteger,
		Default:   Value{Num: 5},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "max_ml4_nested_interp_loop_count",
		Label:     "Max. MUF preempt interp loop nesting level for ML4 (0 = no limit)",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 0},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "max_ml4_preempt_count",
		Label:     "Max. MUF preempt instruction run length for ML4, (0 = no limit)",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 0},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "max_nested_interp_loop_count",
		Label:     "Max. MUF preempt interp loop nesting level",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 16},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "max_object_endowment",
		Label:     "Max. value of an object",
		Group:     "Costs",
		Type:      TypeInteger,
		Default:   Value{Num: 100},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "max_output",
		Label:     "Max. output buffer size",
		Group:     "Spam Limits",
		Type:      TypeInteger,
		Default:   Value{Num: 131071},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "max_pennies",
		Label:     "Max. pennies a player can own",
		Group:     "Currency",
		Type:      TypeInteger,
		Default:   Value{Num: 10000},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "max_plyr_processes",
		Label:     "Concurrent processes allowed per player",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 32},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "max_process_limit",
		Label:     "Total concurrent processes allowed on system",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 400},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "max_propfetch",
		Label:     "Max. size of returned property array",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 1023},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "maxidle",
		Label:     "Maximum idle time before booting",
		Group:     "Idle Boot",
		Type:      TypeTimespan,
		Default:   Value{Span: 7200 * time.Second},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "mcp_muf_mlev",
		Label:     "Mucker Level required to use MCP",
		Group:     "MUF",
		Module:    "MCP",
		Type:      TypeInteger,
		Default:   Value{Num: 3},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "movepennies_muf_mlev",
		Label:     "Mucker Level required to move pennies non-destructively",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 2},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "mpi_continue_after_logout",
		Label:     "Continue executing MPI after logout",
		Group:     "MPI",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "mpi_max_commands",
		Label:     "Max. number of uninterruptable MPI commands",
		Group:     "MPI",
		Type:      TypeInteger,
		Default:   Value{Num: 2048},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "muckname",
		Label:     "Name of the MUCK",
		Group:     "Misc",
		Type:      TypeString,
		Default:   Value{Str: "TygryssMUCK"},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "muf_comments_strict",
		Label:     "MUF comments are strict and not recursive",
		Group:     "MUF",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "new_program_flags",
		Label:     "Initial flags for newly created programs",
		Group:     "Database",
		Type:      TypeString,
		Default:   Value{Str: ""},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
	},
	{
		Name:      "object_cost",
		Label:     "Cost to create an object",
		Group:     "Costs",
		Type:      TypeInteger,
		Default:   Value{Num: 10},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "optimize_muf",
		Label:     "Enable MUF bytecode optimizer",
		Group:     "MUF",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "pause_min",
		Label:     "Min. millisecs between MUF input/output timeslices",
		Group:     "Tuning",
		Type:      TypeInteger,
		Default:   Value{Num: 0},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "pcreate_flags",
		Label:     "Initial flags for newly created players",
		Group:     "Database",
		Type:      TypeString,
		Default:   Value{Str: "B"},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
	},
	{
		Name:      "pennies",
		Label:     "Currency name, plural",
		Group:     "Currency",
		Type:      TypeString,
		Default:   Value{Str: "pennies"},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "pennies_muf_mlev",
		Label:     "Mucker Level required to read the value of pennies, settings above 1 disable {money}",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 1},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "penny",
		Label:     "Currency name",
		Group:     "Currency",
		Type:      TypeString,
		Default:   Value{Str: "penny"},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "penny_rate",
		Label:     "Avg. moves between finding currency",
		Group:     "Currency",
		Type:      TypeInteger,
		Default:   Value{Num: 8},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "periodic_program_purge",
		Label:     "Periodically free unused MUF programs",
		Group:     "Tuning",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "player_name_limit",
		Label:     "Limit on player name length",
		Group:     "Commands",
		Type:      TypeInteger,
		Default:   Value{Num: 16},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:       "player_start",
		Label:      "Home where new players start",
		Group:      "Database",
		Type:       TypeDbref,
		Default:    Value{Ref: ref.GlobalEnvironment},
		ReadMLev:   0,
		WriteMLev:  4,
		ObjType:    ref.TypeRoom,
		HasObjType: true,
	},
	{
		Name:      "playermax",
		Label:     "Limit number of concurrent players allowed",
		Group:     "Connecting",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "playermax_bootmesg",
		Label:     "Max. players connection error message",
		Group:     "Connecting",
		Type:      TypeString,
		Default:   Value{Str: "Sorry, but there are too many players online.  Please try reconnecting in a few minutes."},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "playermax_limit",
		Label:     "Max. player connections allowed",
		Group:     "Connecting",
		Type:      TypeInteger,
		Default:   Value{Num: 56},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "playermax_warnmesg",
		Label:     "Max. players connection login warning",
		Group:     "Connecting",
		Type:      TypeString,
		Default:   Value{Str: "You likely won't be able to connect right now, since too many players are online."},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "pname_history_reporting",
		Label:     "Report player name change history",
		Group:     "Tuning",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "pname_history_threshold",
		Label:     "Length of player name change history",
		Group:     "Tuning",
		Type:      TypeTimespan,
		Default:   Value{Span: 2592000 * time.Second},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "process_timer_limit",
		Label:     "Max. timers per process",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 4},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "quiet_moves",
		Label:     "Suppress basic arrive and depart notifications",
		Group:     "Movement",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "realms_control",
		Label:     "Enable support for realm wizzes",
		Group:     "Database",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "recognize_null_command",
		Label:     "Recognize null command",
		Group:     "Commands",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "register_mesg",
		Label:     "Login registration denied message",
		Group:     "Connecting",
		Type:      TypeString,
		Default:   Value{Str: "Sorry, you can get a character by emailing noreply@yourmuck.com with a charname and password."},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "registration",
		Label:     "Require new players to register manually",
		Group:     "Connecting",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "reserved_names",
		Label:     "String-match list of reserved names",
		Group:     "Database",
		Type:      TypeString,
		Default:   Value{Str: ""},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
	},
	{
		Name:      "reserved_player_names",
		Label:     "String-match list of reserved player names",
		Group:     "Database",
		Type:      TypeString,
		Default:   Value{Str: ""},
		ReadMLev:  0,
		WriteMLev: 4,
		Nullable:  true,
	},
	{
		Name:      "room_cost",
		Label:     "Cost to create an room",
		Group:     "Costs",
		Type:      TypeInteger,
		Default:   Value{Num: 10},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "secure_teleport",
		Label:     "Restrict actions to Jump_OK or controlled rooms",
		Group:     "Movement",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "secure_thing_movement",
		Label:     "Moving things act like player",
		Group:     "Movement",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "secure_who",
		Label:     "Disallow WHO command from login screen and programs",
		Group:     "WHO",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "smtp_auth_type",
		Label:     "SMTP auth type - 0 for CRAM_MD5, 1 for none, 2 for plain, 3 for login",
		Group:     "SMTP",
		Type:      TypeInteger,
		Default:   Value{Num: 3},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "smtp_from_email",
		Label:     "SMTP From user email for the email header",
		Group:     "SMTP",
		Type:      TypeString,
		Default:   Value{Str: "noreply@yourmuck.com"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Nullable:  true,
	},
	{
		Name:      "smtp_from_name",
		Label:     "SMTP From user name for the email header",
		Group:     "SMTP",
		Type:      TypeString,
		Default:   Value{Str: "Your MUCK"},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Nullable:  true,
	},
	{
		Name:      "smtp_no_verify_cert",
		Label:     "SMTP if true, don't verify server certs",
		Group:     "SMTP",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "smtp_password",
		Label:     "SMTP Password",
		Group:     "SMTP",
		Type:      TypeString,
		Default:   Value{Str: ""},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Nullable:  true,
	},
	{
		Name:      "smtp_port",
		Label:     "SMTP Port.  If blank, SMTP will not work.",
		Group:     "SMTP",
		Type:      TypeString,
		Default:   Value{Str: ""},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Nullable:  true,
	},
	{
		Name:      "smtp_server",
		Label:     "SMTP Server Host Name.  If blank, SMTP will not work.",
		Group:     "SMTP",
		Type:      TypeString,
		Default:   Value{Str: ""},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Nullable:  true,
	},
	{
		Name:       "smtp_tls_mode",
		Label:      "SMTP SSL type - 0 for StartTLS, 1 for TLS, 2 for no SSL",
		Group:      "SMTP",
		Type:       TypeInteger,
		Default:    Value{Num: 2},
		ReadMLev:   4,
		WriteMLev:  4,
		GodOnly:    true,
		LegacyName: "smtp_ssl_type",
	},
	{
		Name:      "smtp_user",
		Label:     "SMTP Username",
		Group:     "SMTP",
		Type:      TypeString,
		Default:   Value{Str: ""},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
		Nullable:  true,
	},
	{
		Name:      "start_pennies",
		Label:     "Player starting currency count",
		Group:     "Currency",
		Type:      TypeInteger,
		Default:   Value{Num: 50},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "strict_god_priv",
		Label:     "Only God can touch God's objects",
		Group:     "Misc",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  4,
		WriteMLev: 4,
		GodOnly:   true,
	},
	{
		Name:      "tab_input_replaced_with_space",
		Label:     "Change tab to space when processing input",
		Group:     "Misc",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "teleport_to_player",
		Label:     "Allow using exits linked to players",
		Group:     "Movement",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "thing_darking",
		Label:     "Allow players to set things dark",
		Group:     "Dark",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:       "toad_default_recipient",
		Label:      "Default owner for @toaded player's things",
		Group:      "Database",
		Type:       TypeDbref,
		Default:    Value{Ref: ref.God},
		ReadMLev:   0,
		WriteMLev:  4,
		ObjType:    ref.TypePlayer,
		HasObjType: true,
	},
	{
		Name:      "toad_recycle",
		Label:     "Recycle newly-created toads",
		Group:     "Database",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "use_hostnames",
		Label:     "Resolve IP addresses into hostnames",
		Group:     "WHO",
		Module:    "RESOLVER",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:      "userlog_mlev",
		Label:     "Mucker Level required to write to userlog",
		Group:     "MUF",
		Type:      TypeInteger,
		Default:   Value{Num: 3},
		ReadMLev:  0,
		WriteMLev: 4,
	},
	{
		Name:       "welcome_mpi_what",
		Label:      "Effective 'this' for welcome.txt MPI",
		Group:      "MPI",
		Type:       TypeDbref,
		Default:    Value{Ref: ref.GlobalEnvironment},
		ReadMLev:   4,
		WriteMLev:  4,
		GodOnly:    true,
		ObjType:    ref.NoType,
		HasObjType: true,
	},
	{
		Name:       "welcome_mpi_who",
		Label:      "Effective 'me' for welcome.txt MPI",
		Group:      "MPI",
		Type:       TypeDbref,
		Default:    Value{Ref: ref.God},
		ReadMLev:   4,
		WriteMLev:  4,
		GodOnly:    true,
		ObjType:    ref.TypePlayer,
		HasObjType: true,
	},
	{
		Name:      "who_hides_dark",
		Label:     "Hide dark players from WHO list",
		Group:     "Dark",
		Type:      TypeBoolean,
		Default:   Value{Bool: true},
		ReadMLev:  4,
		WriteMLev: 4,
	},
	{
		Name:      "wiz_vehicles",
		Label:     "Only let Wizards set vehicle bits",
		Group:     "Misc",
		Type:      TypeBoolean,
		Default:   Value{Bool: false},
		ReadMLev:  0,
		WriteMLev: 4,
	},
}

// droppedParams names Fuzzball 7 parameters that Emerald does not implement,
// mapped to the environment variable that replaced each. They are recognised
// only so the importer and @tune can explain themselves instead of failing
// with an unhelpful "unknown parameter".
var droppedParams = map[string]string{
	"server_cipher_preference":   "FBE_TLS_CIPHER_POLICY",
	"ssl_auto_reload_certs":      "FBE_TLS_AUTO_RELOAD",
	"ssl_cert_file":              "FBE_TLS_CERT_FILE",
	"ssl_cipher_preference_list": "FBE_TLS_CIPHER_POLICY",
	"ssl_key_file":               "FBE_TLS_KEY_FILE",
	"ssl_keyfile_passwd":         "FBE_TLS_KEY_PASSWORD",
	"ssl_min_protocol_version":   "FBE_TLS_MIN_VERSION",
	"starttls_allow":             "",
}
