// Code generated from include_internal_defs in Fuzzball 7's
// src/compile.c. DO NOT EDIT.
// Regenerate with: go generate ./internal/muf

package muf

// BuiltinDefines are the $define substitutions the compiler installs
// before reading a program. They are why "}tell", "[]", "desc" and the
// case/when/end/default/endcase idiom work without being primitives.
//
// Definitions whose value is a runtime variable rather than a literal
// are omitted: __version and __muckname depend on the server, and the
// caller supplies them.
var BuiltinDefines = map[string]string{
	"->[]":                    "array_setitem",
	"[..]":                    "array_getrange",
	"[]":                      "array_getitem",
	"[]<-":                    "array_appenditem",
	"__fuzzball__":            "1",
	"array_diff":              "2 array_ndiff",
	"array_intersect":         "2 array_nintersect",
	"array_union":             "2 array_nunion",
	"c_button":                "\"button\"",
	"c_checkbox":              "\"checkbox\"",
	"c_combobox":              "\"combobox\"",
	"c_datum":                 "\"datum\"",
	"c_edit":                  "\"edit\"",
	"c_frame":                 "\"frame\"",
	"c_hrule":                 "\"hrule\"",
	"c_image":                 "\"image\"",
	"c_label":                 "\"text\"",
	"c_listbox":               "\"listbox\"",
	"c_menu":                  "\"menu\"",
	"c_multiedit":             "\"multiedit\"",
	"c_notebook":              "\"notebook\"",
	"c_password":              "\"password\"",
	"c_radiobtn":              "\"radio\"",
	"c_scale":                 "\"scale\"",
	"c_spinner":               "\"spinner\"",
	"c_tree":                  "\"tree\"",
	"c_vrule":                 "\"vrule\"",
	"case":                    "begin dup",
	"conboot":                 "descrboot",
	"concount":                "descrcount",
	"condbref":                "descrdbref",
	"condescr":                "",
	"conhost":                 "descrhost",
	"conidle":                 "descridle",
	"connotify":               "descrnotify",
	"contime":                 "descrtime",
	"conuser":                 "descruser",
	"d_helper":                "\"helper\"",
	"d_simple":                "\"simple\"",
	"d_tabbed":                "\"tabbed\"",
	"dbcmp":                   "=",
	"default":                 "pop 1 if",
	"desc":                    "\"_/de\" getpropstr",
	"descrcon":                "",
	"drop":                    "\"_/dr\" getpropstr",
	"end":                     "break then dup",
	"endcase":                 "pop pop 1 until",
	"err_divzero?":            "0 is_set?",
	"err_fbounds?":            "3 is_set?",
	"err_ibounds?":            "4 is_set?",
	"err_imaginary?":          "2 is_set?",
	"err_nan?":                "1 is_set?",
	"event_wait":              "0 array_make event_waitfor",
	"fail":                    "\"_/fl\" getpropstr",
	"gui_dlog_helper":         "d_helper swap \"panes\" over array_keys array_make \"names\" 4 rotate array_vals array_make 2 array_make_dict gui_dlog_create",
	"gui_dlog_simple":         "d_simple swap 0 array_make_dict gui_dlog_create",
	"gui_dlog_tabbed":         "d_tabbed swap \"panes\" over array_keys array_make \"names\" 4 rotate array_vals array_make 2 array_make_dict gui_dlog_create",
	"idesc":                   "\"_/ide\" getpropstr",
	"name-ok?":                "\"exit\" ext-name-ok?",
	"notify_except":           "1 swap notify_exclude",
	"odrop":                   "\"_/odr\" getpropstr",
	"oecho":                   "\"_/oecho\" getpropstr",
	"ofail":                   "\"_/ofl\" getpropstr",
	"osucc":                   "\"_/osc\" getpropstr",
	"pecho":                   "\"_/pecho\" getpropstr",
	"pname-ok?":               "\"player\" ext-name-ok?",
	"setdesc":                 "\"_/de\" swap setprop",
	"setdrop":                 "\"_/dr\" swap setprop",
	"setfail":                 "\"_/fl\" swap setprop",
	"setidesc":                "\"_/ide\" swap setprop",
	"setodrop":                "\"_/odr\" swap setprop",
	"setoecho":                "\"_/oecho\" swap setprop",
	"setofail":                "\"_/ofl\" swap setprop",
	"setosucc":                "\"_/osc\" swap setprop",
	"setpecho":                "\"_/pecho\" swap setprop",
	"setsucc":                 "\"_/sc\" swap setprop",
	"sorttype_case_ascend":    "0",
	"sorttype_case_descend":   "2",
	"sorttype_caseinsens":     "1",
	"sorttype_descending":     "2",
	"sorttype_nocase_ascend":  "1",
	"sorttype_nocase_descend": "3",
	"sorttype_shuffle":        "4",
	"succ":                    "\"_/sc\" getpropstr",
	"tread":                   "\"__tread\" timer_start { \"TIMER.__tread\" \"READ\" }list event_waitfor nip \"READ\" strcmp if \"\" 0 else read 1 \"__tread\" timer_stop then",
	"truename":                "name",
	"when":                    "if pop",
	"}array":                  "} array_make",
	"}cat":                    "} array_make array_interpret",
	"}dict":                   "} 2 / array_make_dict",
	"}join":                   "} array_make \"\" array_join",
	"}list":                   "} array_make",
	"}tell":                   "} array_make me @ 1 array_make array_notify",
}
