// Code generated from the mlev checks in Fuzzball 7's p_*.c.
// DO NOT EDIT. Regenerate with: go generate ./internal/muf

package muf

// primMLevel is the mucker level a primitive requires.
//
// Upstream guards privileged primitives with "if (mlev < N)" inside
// each implementation. Without these a program at mucker level 1 could
// read passwords, change ownership and boot connections, so this is a
// security surface rather than only a compatibility one.
//
// Where a primitive has several checks, the strictest is recorded: a
// finer-grained gate would need the arguments, which the dispatcher
// does not have.
var primMLevel = map[string]int{
	"ADDPENNIES":           4,
	"ARRAY_GET_IGNORELIST": 3,
	"ARRAY_GET_PROPDIRS":   3,
	"ARRAY_GET_PROPVALS":   3,
	"ARRAY_NOTIFY":         2,
	"ARRAY_NOTIFY_SECURE":  3,
	"BLESSED?":             2,
	"BLESSPROP":            4,
	"CHECKPASSWORD":        4,
	"COMPILE":              4,
	"COPYPLAYER":           4,
	"DESCRBOOT":            4,
	"DESCRBUFSIZE":         3,
	"DESCRDBREF":           3,
	"DESCRFLUSH":           3,
	"DESCRHOST":            4,
	"DESCRIDLE":            3,
	"DESCRIPTORS":          3,
	"DESCRLEASTIDLE":       3,
	"DESCRMOSTIDLE":        3,
	"DESCRNOTIFY":          3,
	"DESCRSECURE?":         3,
	"DESCRTIME":            3,
	"DESCRUSER":            4,
	"DESCR_ARRAY":          3,
	"DESCR_SETUSER":        4,
	"ENTRANCES_ARRAY":      3,
	"EVENT_SEND":           3,
	"FINDNEXT":             2,
	"FIRSTDESCR":           3,
	"FORCE":                4,
	"FORCEDBY":             4,
	"FORCEDBY_ARRAY":       4,
	"FORK":                 3,
	"GETPIDINFO":           3,
	"GETPIDS":              3,
	"IGNORE_ADD":           3,
	"IGNORE_DEL":           3,
	"IGNORING?":            3,
	"KILL":                 3,
	"LASTDESCR":            3,
	"MOVEPENNIES":          4,
	"MOVETO":               3,
	"NEWEXIT":              3,
	"NEWPASSWORD":          4,
	"NEWPLAYER":            4,
	"NEWPROGRAM":           4,
	"NEXTDESCR":            3,
	"NEXTENTRANCE":         3,
	"NEXTOWNED":            2,
	"NEXTPROP":             3,
	"NOTIFY":               2,
	"NOTIFY_EXCLUDE":       2,
	"NOTIFY_NOLISTEN":      2,
	"NOTIFY_SECURE":        3,
	"ONLINE":               3,
	"ONLINE_ARRAY":         3,
	"OTELL":                2,
	"PARSEMPI":             3,
	"PARSEMPIBLESSED":      4,
	"PARSEPROP":            3,
	"PARSEPROPEX":          3,
	"PART_PMATCH":          3,
	"PNAME_HISTORY":        4,
	"PROGRAM_SETLINES":     4,
	"PROPDIR?":             2,
	"QUEUE":                3,
	"SETHEIGHT":            3,
	"SETNAME":              4,
	"SETOWN":               4,
	"SETSYSPARM":           4,
	"SETWIDTH":             3,
	"SMTP_SEND":            4,
	"STATS":                3,
	"STATS_ARRAY":          3,
	"TOADPLAYER":           4,
	"UNBLESSPROP":          4,
	"UNCOMPILE":            4,
	"WATCHPID":             3,
}
