// Code generated from mfun_list in Fuzzball 7's include/mfun.h.
// DO NOT EDIT. Regenerate with: go generate ./internal/mpi

package mpi

// functions describes every MPI function the parser recognises.
//
// The flags decide how a call is handled before its implementation
// ever runs, so they are part of the parser rather than of any one
// function: Parse says the arguments are evaluated first, which
// {and} and {if} switch off so they can stop early; Strip trims
// spaces from them; and PostParse evaluates what comes back.
var functions = map[string]*Func{
	"ABS":       {Name: "ABS", Parse: true, Strip: true, Min: 1, Max: 1},
	"ADD":       {Name: "ADD", Parse: true, Strip: true, Min: 2, Max: 9},
	"AND":       {Name: "AND", Strip: true, Min: 2, Max: 9},
	"ATTR":      {Name: "ATTR", Parse: true, Strip: true, Min: 2, Max: 9},
	"AWAKE":     {Name: "AWAKE", Parse: true, Strip: true, Min: 1, Max: 1},
	"BLESS":     {Name: "BLESS", Parse: true, Strip: true, Min: 1, Max: 2},
	"CENTER":    {Name: "CENTER", Parse: true, Min: 1, Max: 3},
	"COMMAS":    {Name: "COMMAS", Min: 1, Max: 4},
	"CONCAT":    {Name: "CONCAT", Parse: true, Strip: true, Min: 1, Max: 2},
	"CONTAINS":  {Name: "CONTAINS", Parse: true, Strip: true, Min: 1, Max: 2},
	"CONTENTS":  {Name: "CONTENTS", Parse: true, Strip: true, Min: 1, Max: 2},
	"CONTROLS":  {Name: "CONTROLS", Parse: true, Strip: true, Min: 1, Max: 2},
	"CONVSECS":  {Name: "CONVSECS", Parse: true, Strip: true, Min: 1, Max: 1},
	"CONVTIME":  {Name: "CONVTIME", Parse: true, Strip: true, Min: 1, Max: 1},
	"COUNT":     {Name: "COUNT", Parse: true, Min: 1, Max: 2},
	"CREATED":   {Name: "CREATED", Parse: true, Strip: true, Min: 1, Max: 1},
	"DATE":      {Name: "DATE", Parse: true, Strip: true, Min: 0, Max: 1},
	"DBEQ":      {Name: "DBEQ", Parse: true, Strip: true, Min: 2, Max: 2},
	"DEBUG":     {Name: "DEBUG", Min: 1, Max: 1},
	"DEBUGIF":   {Name: "DEBUGIF", Min: 2, Max: 2},
	"DEC":       {Name: "DEC", Parse: true, Strip: true, Min: 1, Max: 2},
	"DEFAULT":   {Name: "DEFAULT", Min: 2, Max: 2},
	"DELAY":     {Name: "DELAY", Parse: true, Strip: true, Min: 2, Max: 2},
	"DELPROP":   {Name: "DELPROP", Parse: true, Strip: true, Min: 1, Max: 2},
	"DESCR":     {Name: "DESCR", Parse: true, Strip: true, Min: 0, Max: 0},
	"DICE":      {Name: "DICE", Parse: true, Strip: true, Min: 1, Max: 3},
	"DIST":      {Name: "DIST", Parse: true, Strip: true, Min: 2, Max: 6},
	"DIV":       {Name: "DIV", Parse: true, Strip: true, Min: 2, Max: 9},
	"EQ":        {Name: "EQ", Parse: true, Min: 2, Max: 2},
	"ESCAPE":    {Name: "ESCAPE", Parse: true, Min: 1, Max: 1},
	"EVAL":      {Name: "EVAL", Parse: true, Min: 1, Max: 1},
	"EVAL!":     {Name: "EVAL!", Parse: true, Min: 1, Max: 1},
	"EXEC":      {Name: "EXEC", Parse: true, Strip: true, Min: 1, Max: 2},
	"EXEC!":     {Name: "EXEC!", Parse: true, Strip: true, Min: 1, Max: 2},
	"EXITS":     {Name: "EXITS", Parse: true, Strip: true, Min: 1, Max: 1},
	"FILTER":    {Name: "FILTER", Min: 3, Max: 5},
	"FLAG?":     {Name: "FLAG?", Parse: true, Strip: true, Min: 2, Max: 2},
	"FLAGS":     {Name: "FLAGS", Parse: true, Strip: true, Min: 1, Max: 1},
	"FOLD":      {Name: "FOLD", Min: 4, Max: 5},
	"FOR":       {Name: "FOR", Min: 5, Max: 5},
	"FORCE":     {Name: "FORCE", Parse: true, Strip: true, Min: 2, Max: 2},
	"FOREACH":   {Name: "FOREACH", Min: 3, Max: 4},
	"FTIME":     {Name: "FTIME", Parse: true, Min: 1, Max: 3},
	"FULLNAME":  {Name: "FULLNAME", Parse: true, Strip: true, Min: 1, Max: 1},
	"FUNC":      {Name: "FUNC", Strip: true, Min: 2, Max: 9},
	"GE":        {Name: "GE", Parse: true, Strip: true, Min: 2, Max: 2},
	"GT":        {Name: "GT", Parse: true, Strip: true, Min: 2, Max: 2},
	"HEIGHT":    {Name: "HEIGHT", Parse: true, Strip: true, Min: 0, Max: 1},
	"HOLDS":     {Name: "HOLDS", Parse: true, Strip: true, Min: 1, Max: 2},
	"IDLE":      {Name: "IDLE", Parse: true, Strip: true, Min: 1, Max: 1},
	"IF":        {Name: "IF", Min: 2, Max: 3},
	"INC":       {Name: "INC", Parse: true, Strip: true, Min: 1, Max: 2},
	"INDEX":     {Name: "INDEX", Parse: true, Strip: true, Min: 1, Max: 2},
	"INDEX!":    {Name: "INDEX!", Parse: true, Strip: true, Min: 1, Max: 2},
	"INSTR":     {Name: "INSTR", Parse: true, Min: 2, Max: 2},
	"ISDBREF":   {Name: "ISDBREF", Parse: true, Strip: true, Min: 1, Max: 1},
	"ISNUM":     {Name: "ISNUM", Parse: true, Strip: true, Min: 1, Max: 1},
	"ISTYPE":    {Name: "ISTYPE", Parse: true, Strip: true, Min: 2, Max: 2},
	"KILL":      {Name: "KILL", Parse: true, Strip: true, Min: 1, Max: 1},
	"LASTUSED":  {Name: "LASTUSED", Parse: true, Strip: true, Min: 1, Max: 1},
	"LCOMMON":   {Name: "LCOMMON", Parse: true, Min: 2, Max: 2},
	"LE":        {Name: "LE", Parse: true, Strip: true, Min: 2, Max: 2},
	"LEFT":      {Name: "LEFT", Parse: true, Min: 1, Max: 3},
	"LEXEC":     {Name: "LEXEC", Parse: true, Strip: true, Min: 1, Max: 2},
	"LINKS":     {Name: "LINKS", Parse: true, Strip: true, Min: 1, Max: 1},
	"LIST":      {Name: "LIST", Parse: true, Strip: true, Min: 1, Max: 2},
	"LISTPROPS": {Name: "LISTPROPS", Parse: true, Strip: true, Min: 1, Max: 3},
	"LIT":       {Name: "LIT", Min: 1, Max: -1},
	"LMEMBER":   {Name: "LMEMBER", Parse: true, Min: 2, Max: 3},
	"LOC":       {Name: "LOC", Parse: true, Strip: true, Min: 1, Max: 1},
	"LOCKED":    {Name: "LOCKED", Parse: true, Strip: true, Min: 2, Max: 2},
	"LRAND":     {Name: "LRAND", Parse: true, Min: 1, Max: 2},
	"LREMOVE":   {Name: "LREMOVE", Parse: true, Min: 2, Max: 2},
	"LSORT":     {Name: "LSORT", Min: 1, Max: 4},
	"LT":        {Name: "LT", Parse: true, Strip: true, Min: 2, Max: 2},
	"LTIMESTR":  {Name: "LTIMESTR", Parse: true, Strip: true, Min: 1, Max: 1},
	"LUNION":    {Name: "LUNION", Parse: true, Min: 2, Max: 2},
	"LUNIQUE":   {Name: "LUNIQUE", Parse: true, Min: 1, Max: 1},
	"MAX":       {Name: "MAX", Parse: true, Strip: true, Min: 2, Max: 2},
	"MIDSTR":    {Name: "MIDSTR", Parse: true, Min: 2, Max: 3},
	"MIN":       {Name: "MIN", Parse: true, Strip: true, Min: 2, Max: 2},
	"MKLIST":    {Name: "MKLIST", Parse: true, Min: 0, Max: 9},
	"MOD":       {Name: "MOD", Parse: true, Strip: true, Min: 2, Max: 9},
	"MODIFIED":  {Name: "MODIFIED", Parse: true, Strip: true, Min: 1, Max: 1},
	"MONEY":     {Name: "MONEY", Parse: true, Strip: true, Min: 1, Max: 1},
	"MUCKNAME":  {Name: "MUCKNAME", Min: 0, Max: 0},
	"MUF":       {Name: "MUF", Parse: true, Min: 2, Max: 2},
	"MULT":      {Name: "MULT", Parse: true, Strip: true, Min: 2, Max: 9},
	"NAME":      {Name: "NAME", Parse: true, Strip: true, Min: 1, Max: 1},
	"NE":        {Name: "NE", Parse: true, Min: 2, Max: 2},
	"NEARBY":    {Name: "NEARBY", Parse: true, Strip: true, Min: 1, Max: 2},
	"NL":        {Name: "NL", Min: 0, Max: 0},
	"NOT":       {Name: "NOT", Parse: true, Strip: true, Min: 1, Max: 1},
	"NULL":      {Name: "NULL", Parse: true, Min: 0, Max: 9},
	"ONLINE":    {Name: "ONLINE", Min: 0, Max: 0},
	"ONTIME":    {Name: "ONTIME", Parse: true, Strip: true, Min: 1, Max: 1},
	"OR":        {Name: "OR", Strip: true, Min: 2, Max: 9},
	"OTELL":     {Name: "OTELL", Parse: true, Min: 1, Max: 3},
	"OWNER":     {Name: "OWNER", Parse: true, Strip: true, Min: 1, Max: 1},
	"PARSE":     {Name: "PARSE", Min: 3, Max: 5},
	"PRONOUNS":  {Name: "PRONOUNS", Parse: true, Min: 1, Max: 2},
	"PROP":      {Name: "PROP", Parse: true, Strip: true, Min: 1, Max: 2},
	"PROP!":     {Name: "PROP!", Parse: true, Strip: true, Min: 1, Max: 2},
	"PROPDIR":   {Name: "PROPDIR", Parse: true, Strip: true, Min: 1, Max: 2},
	"RAND":      {Name: "RAND", Parse: true, Strip: true, Min: 1, Max: 2},
	"REF":       {Name: "REF", Parse: true, Strip: true, Min: 1, Max: 1},
	"REVOKE":    {Name: "REVOKE", Min: 1, Max: 1},
	"RIGHT":     {Name: "RIGHT", Parse: true, Min: 1, Max: 3},
	"SECS":      {Name: "SECS", Min: 0, Max: 0},
	"SELECT":    {Name: "SELECT", Parse: true, Strip: true, Min: 2, Max: 3},
	"SET":       {Name: "SET", Parse: true, Min: 2, Max: 2},
	"SIGN":      {Name: "SIGN", Parse: true, Strip: true, Min: 1, Max: 1},
	"SMATCH":    {Name: "SMATCH", Parse: true, Min: 2, Max: 2},
	"STIMESTR":  {Name: "STIMESTR", Parse: true, Strip: true, Min: 1, Max: 1},
	"STORE":     {Name: "STORE", Parse: true, Strip: true, Min: 2, Max: 3},
	"STRIP":     {Name: "STRIP", Parse: true, Min: 1, Max: -1},
	"STRLEN":    {Name: "STRLEN", Parse: true, Min: 1, Max: 1},
	"SUBLIST":   {Name: "SUBLIST", Parse: true, Min: 1, Max: 4},
	"SUBST":     {Name: "SUBST", Parse: true, Min: 3, Max: 3},
	"SUBT":      {Name: "SUBT", Parse: true, Strip: true, Min: 2, Max: 9},
	"SYSPARM":   {Name: "SYSPARM", Parse: true, Strip: true, Min: 1, Max: 1},
	"TAB":       {Name: "TAB", Min: 0, Max: 0},
	"TELL":      {Name: "TELL", Parse: true, Min: 1, Max: 2},
	"TESTLOCK":  {Name: "TESTLOCK", Parse: true, Strip: true, Min: 2, Max: 4},
	"TIME":      {Name: "TIME", Parse: true, Strip: true, Min: 0, Max: 1},
	"TIMESTR":   {Name: "TIMESTR", Parse: true, Strip: true, Min: 1, Max: 1},
	"TIMESUB":   {Name: "TIMESUB", Parse: true, Strip: true, Min: 3, Max: 4},
	"TIMING":    {Name: "TIMING", Min: 1, Max: 1},
	"TOLOWER":   {Name: "TOLOWER", Parse: true, Min: 1, Max: 1},
	"TOUPPER":   {Name: "TOUPPER", Parse: true, Min: 1, Max: 1},
	"TYPE":      {Name: "TYPE", Parse: true, Strip: true, Min: 1, Max: 1},
	"TZOFFSET":  {Name: "TZOFFSET", Min: 0, Max: 0},
	"UNBLESS":   {Name: "UNBLESS", Parse: true, Strip: true, Min: 1, Max: 2},
	"USECOUNT":  {Name: "USECOUNT", Parse: true, Strip: true, Min: 1, Max: 1},
	"V":         {Name: "V", Parse: true, Strip: true, Min: 1, Max: 1},
	"VERSION":   {Name: "VERSION", Min: 0, Max: 0},
	"WHILE":     {Name: "WHILE", Min: 2, Max: 2},
	"WIDTH":     {Name: "WIDTH", Parse: true, Strip: true, Min: 0, Max: 1},
	"WITH":      {Name: "WITH", Min: 3, Max: 9},
	"XOR":       {Name: "XOR", Parse: true, Strip: true, Min: 2, Max: 2},
}
